# pyproject.toml for tui-app

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tui-app"
version = "0.0.1"
description = "Quick and dirty TUI app framework for tables and forms."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11.2"
dependencies = []

[project.urls]
repository = "https://github.com/dangyogi/tui-app.git"

[project.scripts]
color-display = "tui_app.color_display:run"

[tool.setuptools.package-dir]
tui_app = "tui_app"

[tool.pytest.ini_options]
testpaths = ["tests"]
